# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from civitai.api.coverage_api import CoverageApi


class TestCoverageApi(unittest.TestCase):
    """CoverageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CoverageApi()

    def tearDown(self) -> None:
        pass

    def test_v1_consumer_coverage_get(self) -> None:
        """Test case for v1_consumer_coverage_get

        Get coverage of particular models
        """
        pass


if __name__ == '__main__':
    unittest.main()
