# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from civitai.api.consumption_api import ConsumptionApi


class TestConsumptionApi(unittest.TestCase):
    """ConsumptionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConsumptionApi()

    def tearDown(self) -> None:
        pass

    def test_v1_consumer_consumption_get(self) -> None:
        """Test case for v1_consumer_consumption_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
