# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from civitai.models.read_only_span1 import ReadOnlySpan1

class TestReadOnlySpan1(unittest.TestCase):
    """ReadOnlySpan1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReadOnlySpan1:
        """Test ReadOnlySpan1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReadOnlySpan1`
        """
        model = ReadOnlySpan1()
        if include_optional:
            return ReadOnlySpan1(
                length = 56,
                is_empty = True
            )
        else:
            return ReadOnlySpan1(
        )
        """

    def testReadOnlySpan1(self):
        """Test ReadOnlySpan1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
