# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from civitai.models.job_status_job import JobStatusJob

class TestJobStatusJob(unittest.TestCase):
    """JobStatusJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobStatusJob:
        """Test JobStatusJob
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobStatusJob`
        """
        model = JobStatusJob()
        if include_optional:
            return JobStatusJob(
                model = '',
                params = {
                    'key' : None
                    },
                image_hash = '',
                additional_networks = {
                    'key' : civitai.models.image_job_network_params.ImageJobNetworkParams(
                        type = 'Lora', 
                        strength = 1.337, 
                        trigger_word = '', )
                    },
                destination_url = '',
                base_model = 'SD_1_5',
                store_as_blob = True,
                control_nets = [
                    civitai.models.image_job_control_net.ImageJobControlNet(
                        preprocessor = 'Canny', 
                        weight = 1.337, 
                        start_step = 1.337, 
                        end_step = 1.337, 
                        blob_key = '', 
                        image_url = '', )
                    ],
                cost = 1.337,
                claim_duration = civitai.models.time_span.TimeSpan(
                    ticks = 56, 
                    days = 56, 
                    hours = 56, 
                    milliseconds = 56, 
                    microseconds = 56, 
                    nanoseconds = 56, 
                    minutes = 56, 
                    seconds = 56, 
                    total_days = 1.337, 
                    total_hours = 1.337, 
                    total_milliseconds = 1.337, 
                    total_microseconds = 1.337, 
                    total_nanoseconds = 1.337, 
                    total_minutes = 1.337, 
                    total_seconds = 1.337, ),
                type = '',
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expire_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                webhook = '',
                properties = {
                    'key' : None
                    },
                max_retry_attempt = 56,
                dependencies = [
                    ''
                    ],
                issued_by = '',
                training_data = '',
                custom_cost = 1.337,
                output = '',
                image_url = '',
                transformer = 'Canny',
                destination_blob_key = '',
                media_url = '',
                threshold = 1.337,
                model_id = 56,
                action = 'Upload',
                assets = {
                    'key' : civitai.models.image_job_network_params.ImageJobNetworkParams(
                        type = 'Lora', 
                        strength = 1.337, 
                        trigger_word = '', )
                    }
            )
        else:
            return JobStatusJob(
        )
        """

    def testJobStatusJob(self):
        """Test JobStatusJob"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
