# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from civitai.models.method_impl_attributes import MethodImplAttributes

class TestMethodImplAttributes(unittest.TestCase):
    """MethodImplAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMethodImplAttributes(self):
        """Test MethodImplAttributes"""
        # inst = MethodImplAttributes()

if __name__ == '__main__':
    unittest.main()
