# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from civitai.models.text_to_image_job_request import TextToImageJobRequest

class TestTextToImageJobRequest(unittest.TestCase):
    """TextToImageJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TextToImageJobRequest:
        """Test TextToImageJobRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TextToImageJobRequest`
        """
        model = TextToImageJobRequest()
        if include_optional:
            return TextToImageJobRequest(
                quantity = 1,
                model = '',
                additional_networks = {
                    'key' : civitai.models.image_job_network_params.ImageJobNetworkParams(
                        type = 'Lora', 
                        strength = 1.337, 
                        trigger_word = '', )
                    },
                control_nets = [
                    civitai.models.image_job_control_net.ImageJobControlNet(
                        preprocessor = 'Canny', 
                        weight = 1.337, 
                        start_step = 1.337, 
                        end_step = 1.337, 
                        blob_key = '', 
                        image_url = '', )
                    ],
                params = civitai.models.image_job_params.ImageJobParams(
                    prompt = '', 
                    negative_prompt = '', 
                    scheduler = 'EulerA', 
                    steps = 1, 
                    cfg_scale = 1, 
                    width = 64, 
                    height = 64, 
                    seed = -1, 
                    clip_skip = 56, )
            )
        else:
            return TextToImageJobRequest(
        )
        """

    def testTextToImageJobRequest(self):
        """Test TextToImageJobRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
