# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from civitai.models.image_job_params import ImageJobParams

class TestImageJobParams(unittest.TestCase):
    """ImageJobParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageJobParams:
        """Test ImageJobParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageJobParams`
        """
        model = ImageJobParams()
        if include_optional:
            return ImageJobParams(
                prompt = '',
                negative_prompt = '',
                scheduler = 'EulerA',
                steps = 1,
                cfg_scale = 1,
                width = 64,
                height = 64,
                seed = -1,
                clip_skip = 56
            )
        else:
            return ImageJobParams(
                width = 64,
                height = 64,
        )
        """

    def testImageJobParams(self):
        """Test ImageJobParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
