# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from civitai.models.calling_conventions import CallingConventions

class TestCallingConventions(unittest.TestCase):
    """CallingConventions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCallingConventions(self):
        """Test CallingConventions"""
        # inst = CallingConventions()

if __name__ == '__main__':
    unittest.main()
