# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from civitai.models.wd_tagging_job_request import WDTaggingJobRequest

class TestWDTaggingJobRequest(unittest.TestCase):
    """WDTaggingJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WDTaggingJobRequest:
        """Test WDTaggingJobRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WDTaggingJobRequest`
        """
        model = WDTaggingJobRequest()
        if include_optional:
            return WDTaggingJobRequest(
                model = '0',
                media_url = '',
                threshold = 1.337
            )
        else:
            return WDTaggingJobRequest(
                model = '0',
                media_url = '',
        )
        """

    def testWDTaggingJobRequest(self):
        """Test WDTaggingJobRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
