# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from civitai.models.image_resource_training_job_request import ImageResourceTrainingJobRequest

class TestImageResourceTrainingJobRequest(unittest.TestCase):
    """ImageResourceTrainingJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageResourceTrainingJobRequest:
        """Test ImageResourceTrainingJobRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageResourceTrainingJobRequest`
        """
        model = ImageResourceTrainingJobRequest()
        if include_optional:
            return ImageResourceTrainingJobRequest(
                model = '',
                training_data = '',
                params = {
                    'key' : null
                    }
            )
        else:
            return ImageResourceTrainingJobRequest(
        )
        """

    def testImageResourceTrainingJobRequest(self):
        """Test ImageResourceTrainingJobRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
