# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from civitai.models.method_attributes import MethodAttributes

class TestMethodAttributes(unittest.TestCase):
    """MethodAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMethodAttributes(self):
        """Test MethodAttributes"""
        # inst = MethodAttributes()

if __name__ == '__main__':
    unittest.main()
