# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from civitai.models.job_request_priority import JobRequestPriority

class TestJobRequestPriority(unittest.TestCase):
    """JobRequestPriority unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobRequestPriority:
        """Test JobRequestPriority
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobRequestPriority`
        """
        model = JobRequestPriority()
        if include_optional:
            return JobRequestPriority(
                value = 56,
                min = 56,
                max = 56
            )
        else:
            return JobRequestPriority(
        )
        """

    def testJobRequestPriority(self):
        """Test JobRequestPriority"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
