# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from civitai.models.media_tagging_job_request import MediaTaggingJobRequest

class TestMediaTaggingJobRequest(unittest.TestCase):
    """MediaTaggingJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MediaTaggingJobRequest:
        """Test MediaTaggingJobRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MediaTaggingJobRequest`
        """
        model = MediaTaggingJobRequest()
        if include_optional:
            return MediaTaggingJobRequest(
                model_id = 56,
                media_url = ''
            )
        else:
            return MediaTaggingJobRequest(
                model_id = 56,
                media_url = '',
        )
        """

    def testMediaTaggingJobRequest(self):
        """Test MediaTaggingJobRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
