# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from civitai.models.unpin_blob_request import UnpinBlobRequest

class TestUnpinBlobRequest(unittest.TestCase):
    """UnpinBlobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnpinBlobRequest:
        """Test UnpinBlobRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnpinBlobRequest`
        """
        model = UnpinBlobRequest()
        if include_optional:
            return UnpinBlobRequest(
                key = ''
            )
        else:
            return UnpinBlobRequest(
        )
        """

    def testUnpinBlobRequest(self):
        """Test UnpinBlobRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
