# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from civitai.models.ranged_priority import RangedPriority

class TestRangedPriority(unittest.TestCase):
    """RangedPriority unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RangedPriority:
        """Test RangedPriority
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RangedPriority`
        """
        model = RangedPriority()
        if include_optional:
            return RangedPriority(
                min = 56,
                max = 56
            )
        else:
            return RangedPriority(
        )
        """

    def testRangedPriority(self):
        """Test RangedPriority"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
