# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from civitai.models.module_handle import ModuleHandle

class TestModuleHandle(unittest.TestCase):
    """ModuleHandle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModuleHandle:
        """Test ModuleHandle
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModuleHandle`
        """
        model = ModuleHandle()
        if include_optional:
            return ModuleHandle(
                md_stream_version = 56
            )
        else:
            return ModuleHandle(
        )
        """

    def testModuleHandle(self):
        """Test ModuleHandle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
