# coding: utf-8

# flake8: noqa
"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from civitai.models.air import AIR
from civitai.models.assembly import Assembly
from civitai.models.asset_type import AssetType
from civitai.models.base_model import SDBaseModel
from civitai.models.calling_conventions import CallingConventions
from civitai.models.clear_asset_request import ClearAssetRequest
from civitai.models.comfy_job import ComfyJob
from civitai.models.comfy_job_request import ComfyJobRequest
from civitai.models.constructor_info import ConstructorInfo
from civitai.models.consumption_details import ConsumptionDetails
from civitai.models.copy_asset_request import CopyAssetRequest
from civitai.models.custom_attribute_data import CustomAttributeData
from civitai.models.custom_attribute_named_argument import CustomAttributeNamedArgument
from civitai.models.custom_attribute_typed_argument import CustomAttributeTypedArgument
from civitai.models.delete_blob_request import DeleteBlobRequest
from civitai.models.event_attributes import EventAttributes
from civitai.models.event_info import EventInfo
from civitai.models.exception import Exception
from civitai.models.field_attributes import FieldAttributes
from civitai.models.field_info import FieldInfo
from civitai.models.fixed_priority import FixedPriority
from civitai.models.generic_parameter_attributes import GenericParameterAttributes
from civitai.models.get_blob_request import GetBlobRequest
from civitai.models.image_embedding_job import ImageEmbeddingJob
from civitai.models.image_embedding_job_request import ImageEmbeddingJobRequest
from civitai.models.image_job_control_net import ImageJobControlNet
from civitai.models.image_job_network_params import ImageJobNetworkParams
from civitai.models.image_job_params import ImageJobParams
from civitai.models.image_resource_training_job import ImageResourceTrainingJob
from civitai.models.image_resource_training_job_request import ImageResourceTrainingJobRequest
from civitai.models.image_transform_job import ImageTransformJob
from civitai.models.image_transform_job_request import ImageTransformJobRequest
from civitai.models.image_transformer import ImageTransformer
from civitai.models.job import Job
from civitai.models.job_event import JobEvent
from civitai.models.job_event_type import JobEventType
from civitai.models.job_request import JobRequest
from civitai.models.job_request_priority import JobRequestPriority
from civitai.models.job_status import JobStatus
from civitai.models.job_status_collection import JobStatusCollection
from civitai.models.job_status_job import JobStatusJob
from civitai.models.job_support import JobSupport
from civitai.models.job_template_list import JobTemplateList
from civitai.models.job_template_list_jobs_inner import JobTemplateListJobsInner
from civitai.models.layout_kind import LayoutKind
from civitai.models.media_tagging_job import MediaTaggingJob
from civitai.models.media_tagging_job_request import MediaTaggingJobRequest
from civitai.models.member_info import MemberInfo
from civitai.models.member_types import MemberTypes
from civitai.models.method_attributes import MethodAttributes
from civitai.models.method_base import MethodBase
from civitai.models.method_impl_attributes import MethodImplAttributes
from civitai.models.method_info import MethodInfo
from civitai.models.model_error import ModelError
from civitai.models.model_state_entry import ModelStateEntry
from civitai.models.model_validation_state import ModelValidationState
from civitai.models.module import Module
from civitai.models.module_handle import ModuleHandle
from civitai.models.parameter_attributes import ParameterAttributes
from civitai.models.parameter_info import ParameterInfo
from civitai.models.pin_blob_request import PinBlobRequest
from civitai.models.pin_model_job import PinModelJob
from civitai.models.ping_job import PingJob
from civitai.models.prepare_model_action import PrepareModelAction
from civitai.models.prepare_model_job import PrepareModelJob
from civitai.models.prepare_model_job_request import PrepareModelJobRequest
from civitai.models.problem_details import ProblemDetails
from civitai.models.property_attributes import PropertyAttributes
from civitai.models.property_info import PropertyInfo
from civitai.models.provider import Provider
from civitai.models.provider_asset_availability import ProviderAssetAvailability
from civitai.models.provider_job_queue_position import ProviderJobQueuePosition
from civitai.models.provider_job_status import ProviderJobStatus
from civitai.models.query_jobs_request import QueryJobsRequest
from civitai.models.query_jobs_result import QueryJobsResult
from civitai.models.ranged_priority import RangedPriority
from civitai.models.read_only_span1 import ReadOnlySpan1
from civitai.models.reboot_worker_job import RebootWorkerJob
from civitai.models.reboot_worker_job_request import RebootWorkerJobRequest
from civitai.models.runtime_field_handle import RuntimeFieldHandle
from civitai.models.runtime_method_handle import RuntimeMethodHandle
from civitai.models.runtime_type_handle import RuntimeTypeHandle
from civitai.models.scheduler import Scheduler
from civitai.models.security_rule_set import SecurityRuleSet
from civitai.models.struct_layout_attribute import StructLayoutAttribute
from civitai.models.taint_job_request import TaintJobRequest
from civitai.models.taint_jobs_request import TaintJobsRequest
from civitai.models.taint_jobs_result import TaintJobsResult
from civitai.models.text_to_image_job import TextToImageJob
from civitai.models.text_to_image_job_request import TextToImageJobRequest
from civitai.models.time_span import TimeSpan
from civitai.models.type import Type
from civitai.models.type_attributes import TypeAttributes
from civitai.models.type_info import TypeInfo
from civitai.models.unpin_blob_request import UnpinBlobRequest
from civitai.models.upload_blob_request import UploadBlobRequest
from civitai.models.wd_tagging_job import WDTaggingJob
from civitai.models.wd_tagging_job_request import WDTaggingJobRequest
from civitai.models.worker_asset_availability import WorkerAssetAvailability
