# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MethodAttributes(str, Enum):
    """
    MethodAttributes
    """

    """
    allowed enum values
    """
    PRIVATESCOPE = 'PrivateScope'
    PRIVATE = 'Private'
    FAMANDASSEM = 'FamANDAssem'
    ASSEMBLY = 'Assembly'
    FAMILY = 'Family'
    FAMORASSEM = 'FamORAssem'
    PUBLIC = 'Public'
    MEMBERACCESSMASK = 'MemberAccessMask'
    UNMANAGEDEXPORT = 'UnmanagedExport'
    STATIC = 'Static'
    FINAL = 'Final'
    VIRTUAL = 'Virtual'
    HIDEBYSIG = 'HideBySig'
    NEWSLOT = 'NewSlot'
    CHECKACCESSONOVERRIDE = 'CheckAccessOnOverride'
    ABSTRACT = 'Abstract'
    SPECIALNAME = 'SpecialName'
    RTSPECIALNAME = 'RTSpecialName'
    PINVOKEIMPL = 'PinvokeImpl'
    HASSECURITY = 'HasSecurity'
    REQUIRESECOBJECT = 'RequireSecObject'
    RESERVEDMASK = 'ReservedMask'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MethodAttributes from a JSON string"""
        return cls(json.loads(json_str))


