# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MethodImplAttributes(str, Enum):
    """
    MethodImplAttributes
    """

    """
    allowed enum values
    """
    IL = 'IL'
    NATIVE = 'Native'
    OPTIL = 'OPTIL'
    CODETYPEMASK = 'CodeTypeMask'
    MANAGEDMASK = 'ManagedMask'
    NOINLINING = 'NoInlining'
    FORWARDREF = 'ForwardRef'
    SYNCHRONIZED = 'Synchronized'
    NOOPTIMIZATION = 'NoOptimization'
    PRESERVESIG = 'PreserveSig'
    AGGRESSIVEINLINING = 'AggressiveInlining'
    AGGRESSIVEOPTIMIZATION = 'AggressiveOptimization'
    INTERNALCALL = 'InternalCall'
    MAXMETHODIMPLVAL = 'MaxMethodImplVal'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MethodImplAttributes from a JSON string"""
        return cls(json.loads(json_str))


