# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SecurityRuleSet(str, Enum):
    """
    SecurityRuleSet
    """

    """
    allowed enum values
    """
    NONE = 'None'
    LEVEL1 = 'Level1'
    LEVEL2 = 'Level2'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SecurityRuleSet from a JSON string"""
        return cls(json.loads(json_str))


