# coding: utf-8

"""
    Civitai Orchestration Consumer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TypeAttributes(str, Enum):
    """
    TypeAttributes
    """

    """
    allowed enum values
    """
    NOTPUBLIC = 'NotPublic'
    PUBLIC = 'Public'
    NESTEDPUBLIC = 'NestedPublic'
    NESTEDPRIVATE = 'NestedPrivate'
    NESTEDFAMILY = 'NestedFamily'
    NESTEDASSEMBLY = 'NestedAssembly'
    NESTEDFAMANDASSEM = 'NestedFamANDAssem'
    VISIBILITYMASK = 'VisibilityMask'
    SEQUENTIALLAYOUT = 'SequentialLayout'
    EXPLICITLAYOUT = 'ExplicitLayout'
    LAYOUTMASK = 'LayoutMask'
    INTERFACE = 'Interface'
    ABSTRACT = 'Abstract'
    SEALED = 'Sealed'
    SPECIALNAME = 'SpecialName'
    RTSPECIALNAME = 'RTSpecialName'
    IMPORT = 'Import'
    SERIALIZABLE = 'Serializable'
    WINDOWSRUNTIME = 'WindowsRuntime'
    UNICODECLASS = 'UnicodeClass'
    AUTOCLASS = 'AutoClass'
    STRINGFORMATMASK = 'StringFormatMask'
    HASSECURITY = 'HasSecurity'
    RESERVEDMASK = 'ReservedMask'
    BEFOREFIELDINIT = 'BeforeFieldInit'
    CUSTOMFORMATMASK = 'CustomFormatMask'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TypeAttributes from a JSON string"""
        return cls(json.loads(json_str))


